apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    repo: oci://quay.io/cilium/charts/
    version: 1.19.4
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - networking/httproute-hubble.yaml
  - networking/l2-ipv4-pool.yaml
  - networking/gateway-ipv4.yaml
