apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: peer-config-ipv6
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  ebgpMultihop: 10
  families:
    - afi: ipv6
      safi: unicast
      advertisements:
        matchLabels:
          family: ipv6