apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: peer-config-ipv4
spec:
  timers:
    holdTimeSeconds: 30
    keepAliveTimeSeconds: 10
  ebgpMultihop: 1
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          family: ipv4