apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atv4-compassuol-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/donato-marcos/k8s-configs.git
    path: apps/atv4-compassuol/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: atv4-compassuol-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
