# longhorn-values.yaml
global:
  timezone: "America/Sao_Paulo"
service:
  ui:
    type: ClusterIP
persistence:
  defaultClassReplicaCount: 3
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
preUpgradeChecker:
  jobEnabled: false