apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atv4-compassuol-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/donato-marcos/k8s-apps.git
    path: apps/atv4-compassuol/overlays/dev
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: atv4-compassuol-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
