apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/
    version: v1.20.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - cloudflare-api-token-secret.yaml
  - certificates/wildcard-prod.yaml
  - certificates/wildcard-staging.yaml
  - issuers/prod-clousterissuer.yaml
  - issuers/staging-clousterissuer.yaml
