apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: DEBUG
              value: "True"  # Habilita debug em DEV
            - name: ENVIRONMENT
              value: "dev"
---
# Patch para ajustar o HPA em DEV (desabilita ou reduz)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
spec:
  minReplicas: 1
  maxReplicas: 2  # Limita escala em DEV